// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: packet.proto

package pb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Timestamp struct {
	Seconds              int64    `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanos                int32    `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timestamp) Reset()         { *m = Timestamp{} }
func (m *Timestamp) String() string { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()    {}
func (*Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{0}
}
func (m *Timestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timestamp.Unmarshal(m, b)
}
func (m *Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timestamp.Marshal(b, m, deterministic)
}
func (m *Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamp.Merge(m, src)
}
func (m *Timestamp) XXX_Size() int {
	return xxx_messageInfo_Timestamp.Size(m)
}
func (m *Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamp proto.InternalMessageInfo

func (m *Timestamp) GetSeconds() int64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *Timestamp) GetNanos() int32 {
	if m != nil {
		return m.Nanos
	}
	return 0
}

type Tag struct {
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*Tag_String_
	//	*Tag_Int64
	//	*Tag_Double
	//	*Tag_Bytes
	//	*Tag_Bool
	//	*Tag_DurationNs
	//	*Tag_Timestamp
	Value                isTag_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{1}
}
func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

type isTag_Value interface {
	isTag_Value()
}

type Tag_String_ struct {
	String_ []byte `protobuf:"bytes,2,opt,name=string,proto3,oneof" json:"string,omitempty"`
}
type Tag_Int64 struct {
	Int64 int64 `protobuf:"varint,3,opt,name=int64,proto3,oneof" json:"int64,omitempty"`
}
type Tag_Double struct {
	Double float64 `protobuf:"fixed64,4,opt,name=double,proto3,oneof" json:"double,omitempty"`
}
type Tag_Bytes struct {
	Bytes []byte `protobuf:"bytes,5,opt,name=bytes,proto3,oneof" json:"bytes,omitempty"`
}
type Tag_Bool struct {
	Bool bool `protobuf:"varint,6,opt,name=bool,proto3,oneof" json:"bool,omitempty"`
}
type Tag_DurationNs struct {
	DurationNs int64 `protobuf:"varint,7,opt,name=duration_ns,json=durationNs,proto3,oneof" json:"duration_ns,omitempty"`
}
type Tag_Timestamp struct {
	Timestamp *Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3,oneof" json:"timestamp,omitempty"`
}

func (*Tag_String_) isTag_Value()    {}
func (*Tag_Int64) isTag_Value()      {}
func (*Tag_Double) isTag_Value()     {}
func (*Tag_Bytes) isTag_Value()      {}
func (*Tag_Bool) isTag_Value()       {}
func (*Tag_DurationNs) isTag_Value() {}
func (*Tag_Timestamp) isTag_Value()  {}

func (m *Tag) GetValue() isTag_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Tag) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Tag) GetString_() []byte {
	if x, ok := m.GetValue().(*Tag_String_); ok {
		return x.String_
	}
	return nil
}

func (m *Tag) GetInt64() int64 {
	if x, ok := m.GetValue().(*Tag_Int64); ok {
		return x.Int64
	}
	return 0
}

func (m *Tag) GetDouble() float64 {
	if x, ok := m.GetValue().(*Tag_Double); ok {
		return x.Double
	}
	return 0
}

func (m *Tag) GetBytes() []byte {
	if x, ok := m.GetValue().(*Tag_Bytes); ok {
		return x.Bytes
	}
	return nil
}

func (m *Tag) GetBool() bool {
	if x, ok := m.GetValue().(*Tag_Bool); ok {
		return x.Bool
	}
	return false
}

func (m *Tag) GetDurationNs() int64 {
	if x, ok := m.GetValue().(*Tag_DurationNs); ok {
		return x.DurationNs
	}
	return 0
}

func (m *Tag) GetTimestamp() *Timestamp {
	if x, ok := m.GetValue().(*Tag_Timestamp); ok {
		return x.Timestamp
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Tag) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Tag_String_)(nil),
		(*Tag_Int64)(nil),
		(*Tag_Double)(nil),
		(*Tag_Bytes)(nil),
		(*Tag_Bool)(nil),
		(*Tag_DurationNs)(nil),
		(*Tag_Timestamp)(nil),
	}
}

type Event struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Scope                []string `protobuf:"bytes,2,rep,name=scope,proto3" json:"scope,omitempty"`
	TimestampOffsetNs    int64    `protobuf:"varint,3,opt,name=timestamp_offset_ns,json=timestampOffsetNs,proto3" json:"timestamp_offset_ns,omitempty"`
	Tags                 []*Tag   `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{2}
}
func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Event) GetScope() []string {
	if m != nil {
		return m.Scope
	}
	return nil
}

func (m *Event) GetTimestampOffsetNs() int64 {
	if m != nil {
		return m.TimestampOffsetNs
	}
	return 0
}

func (m *Event) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Packet struct {
	Application          string     `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	ApplicationVersion   string     `protobuf:"bytes,2,opt,name=application_version,json=applicationVersion,proto3" json:"application_version,omitempty"`
	Instance             string     `protobuf:"bytes,3,opt,name=instance,proto3" json:"instance,omitempty"`
	StartTimestamp       *Timestamp `protobuf:"bytes,4,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	SendOffsetNs         int64      `protobuf:"varint,5,opt,name=send_offset_ns,json=sendOffsetNs,proto3" json:"send_offset_ns,omitempty"`
	Events               []*Event   `protobuf:"bytes,6,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{3}
}
func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetApplication() string {
	if m != nil {
		return m.Application
	}
	return ""
}

func (m *Packet) GetApplicationVersion() string {
	if m != nil {
		return m.ApplicationVersion
	}
	return ""
}

func (m *Packet) GetInstance() string {
	if m != nil {
		return m.Instance
	}
	return ""
}

func (m *Packet) GetStartTimestamp() *Timestamp {
	if m != nil {
		return m.StartTimestamp
	}
	return nil
}

func (m *Packet) GetSendOffsetNs() int64 {
	if m != nil {
		return m.SendOffsetNs
	}
	return 0
}

func (m *Packet) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type Record struct {
	Application           string     `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	ApplicationVersion    string     `protobuf:"bytes,2,opt,name=application_version,json=applicationVersion,proto3" json:"application_version,omitempty"`
	Instance              string     `protobuf:"bytes,3,opt,name=instance,proto3" json:"instance,omitempty"`
	SourceAddr            string     `protobuf:"bytes,4,opt,name=source_addr,json=sourceAddr,proto3" json:"source_addr,omitempty"`
	Timestamp             *Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TimestampCorrectionNs int64      `protobuf:"varint,6,opt,name=timestamp_correction_ns,json=timestampCorrectionNs,proto3" json:"timestamp_correction_ns,omitempty"`
	Tags                  []*Tag     `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}   `json:"-"`
	XXX_unrecognized      []byte     `json:"-"`
	XXX_sizecache         int32      `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{4}
}
func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetApplication() string {
	if m != nil {
		return m.Application
	}
	return ""
}

func (m *Record) GetApplicationVersion() string {
	if m != nil {
		return m.ApplicationVersion
	}
	return ""
}

func (m *Record) GetInstance() string {
	if m != nil {
		return m.Instance
	}
	return ""
}

func (m *Record) GetSourceAddr() string {
	if m != nil {
		return m.SourceAddr
	}
	return ""
}

func (m *Record) GetTimestamp() *Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Record) GetTimestampCorrectionNs() int64 {
	if m != nil {
		return m.TimestampCorrectionNs
	}
	return 0
}

func (m *Record) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterType((*Timestamp)(nil), "eventkit.Timestamp")
	proto.RegisterType((*Tag)(nil), "eventkit.Tag")
	proto.RegisterType((*Event)(nil), "eventkit.Event")
	proto.RegisterType((*Packet)(nil), "eventkit.Packet")
	proto.RegisterType((*Record)(nil), "eventkit.Record")
}

func init() { proto.RegisterFile("packet.proto", fileDescriptor_e9ef1a6541f9f9e7) }

var fileDescriptor_e9ef1a6541f9f9e7 = []byte{
	// 527 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0xcd, 0x6e, 0x13, 0x31,
	0x10, 0xc7, 0xb3, 0xd9, 0x8f, 0x64, 0x27, 0xa1, 0x05, 0xa7, 0x80, 0x85, 0x84, 0xba, 0x8d, 0x90,
	0xd8, 0x53, 0x22, 0x5a, 0xd4, 0x0b, 0x5c, 0x28, 0x42, 0xca, 0xa9, 0x20, 0xab, 0xe2, 0xc0, 0x25,
	0xf2, 0xee, 0xba, 0x61, 0x49, 0x62, 0xaf, 0x6c, 0x6f, 0xa4, 0xde, 0xfb, 0x2c, 0x3c, 0x20, 0x4f,
	0x80, 0xec, 0xfd, 0xbc, 0xe4, 0xda, 0x9b, 0xff, 0xf3, 0x9f, 0x19, 0x8f, 0x7f, 0x3b, 0x5a, 0x98,
	0x16, 0x34, 0xdd, 0x32, 0xbd, 0x28, 0xa4, 0xd0, 0x02, 0x8d, 0xd9, 0x81, 0x71, 0xbd, 0xcd, 0xf5,
	0xfc, 0x13, 0x84, 0x77, 0xf9, 0x9e, 0x29, 0x4d, 0xf7, 0x05, 0xc2, 0x30, 0x52, 0x2c, 0x15, 0x3c,
	0x53, 0xd8, 0x89, 0x9c, 0xd8, 0x25, 0x8d, 0x44, 0x67, 0xe0, 0x73, 0xca, 0x85, 0xc2, 0xc3, 0xc8,
	0x89, 0x7d, 0x52, 0x89, 0xf9, 0x3f, 0x07, 0xdc, 0x3b, 0xba, 0x41, 0xcf, 0xc1, 0xdd, 0xb2, 0x07,
	0x5b, 0x13, 0x12, 0x73, 0x44, 0x18, 0x02, 0xa5, 0x65, 0xce, 0x37, 0xb6, 0x60, 0xba, 0x1a, 0x90,
	0x5a, 0xa3, 0x57, 0xe0, 0xe7, 0x5c, 0x5f, 0x7f, 0xc4, 0xae, 0xb9, 0x61, 0x35, 0x20, 0x95, 0x34,
	0x15, 0x99, 0x28, 0x93, 0x1d, 0xc3, 0x5e, 0xe4, 0xc4, 0x8e, 0xa9, 0xa8, 0xb4, 0xa9, 0x48, 0x1e,
	0x34, 0x53, 0xd8, 0xaf, 0x5b, 0x55, 0x12, 0x9d, 0x81, 0x97, 0x08, 0xb1, 0xc3, 0x41, 0xe4, 0xc4,
	0xe3, 0xd5, 0x80, 0x58, 0x85, 0x2e, 0x60, 0x92, 0x95, 0x92, 0xea, 0x5c, 0xf0, 0x35, 0x57, 0x78,
	0x54, 0xdf, 0x02, 0x4d, 0xf0, 0x56, 0xa1, 0x2b, 0x08, 0x75, 0xf3, 0x66, 0x3c, 0x8e, 0x9c, 0x78,
	0x72, 0x39, 0x5b, 0x34, 0x44, 0x16, 0x2d, 0x8e, 0xd5, 0x80, 0x74, 0x79, 0x37, 0x23, 0xf0, 0x0f,
	0x74, 0x57, 0xb2, 0xf9, 0xa3, 0x03, 0xfe, 0x37, 0x93, 0x8c, 0x10, 0x78, 0x9c, 0xee, 0x59, 0xfd,
	0x6e, 0x7b, 0x36, 0xa0, 0x54, 0x2a, 0x0a, 0x86, 0x87, 0x91, 0x1b, 0x87, 0xa4, 0x12, 0x68, 0x01,
	0xb3, 0xb6, 0xd3, 0x5a, 0xdc, 0xdf, 0x2b, 0xa6, 0xcd, 0x70, 0x16, 0x01, 0x79, 0xd1, 0x5a, 0xdf,
	0xad, 0x73, 0xab, 0xd0, 0x05, 0x78, 0x9a, 0x6e, 0x14, 0xf6, 0x22, 0x37, 0x9e, 0x5c, 0x3e, 0xeb,
	0x0d, 0x47, 0x37, 0xc4, 0x5a, 0xf3, 0xc7, 0x21, 0x04, 0x3f, 0xec, 0x37, 0x45, 0x11, 0x4c, 0x68,
	0x51, 0xec, 0xf2, 0xd4, 0x3e, 0xb0, 0x1e, 0xa7, 0x1f, 0x42, 0x4b, 0x98, 0xf5, 0xe4, 0xfa, 0xc0,
	0xa4, 0x32, 0x99, 0x43, 0x9b, 0x89, 0x7a, 0xd6, 0xcf, 0xca, 0x41, 0x6f, 0x60, 0x9c, 0x73, 0xa5,
	0x29, 0x4f, 0x99, 0x9d, 0x32, 0x24, 0xad, 0x46, 0x9f, 0xe1, 0x54, 0x69, 0x2a, 0xf5, 0xba, 0x83,
	0xe8, 0x1d, 0x85, 0x48, 0x4e, 0x6c, 0x6e, 0xb7, 0x63, 0xef, 0xe0, 0x44, 0x31, 0x9e, 0xf5, 0x28,
	0xf8, 0x96, 0xc2, 0xd4, 0x44, 0x5b, 0x00, 0xef, 0x21, 0xb0, 0xbd, 0x14, 0x0e, 0x2c, 0x82, 0xd3,
	0xae, 0xb5, 0x65, 0x4f, 0x6a, 0x7b, 0xfe, 0x77, 0x08, 0x01, 0x61, 0xa9, 0x90, 0xd9, 0x53, 0x63,
	0x38, 0x87, 0x89, 0x12, 0xa5, 0x4c, 0xd9, 0x9a, 0x66, 0x99, 0xb4, 0x08, 0x42, 0x02, 0x55, 0xe8,
	0x4b, 0x96, 0x49, 0xf4, 0xa1, 0xbf, 0x66, 0xfe, 0x71, 0x42, 0x5d, 0x16, 0xba, 0x86, 0xd7, 0xdd,
	0x9e, 0xa4, 0x42, 0x4a, 0x96, 0x36, 0x8b, 0x1c, 0x58, 0x4a, 0x2f, 0x5b, 0xfb, 0x6b, 0xeb, 0xf6,
	0xf6, 0x65, 0x74, 0x74, 0x5f, 0x6e, 0xce, 0x7f, 0xbd, 0xdd, 0xe4, 0xfa, 0x77, 0x99, 0x2c, 0x52,
	0xb1, 0x5f, 0xfe, 0xd1, 0x62, 0x97, 0x8b, 0x65, 0x93, 0xb7, 0x2c, 0x92, 0x24, 0xb0, 0xbf, 0x86,
	0xab, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0f, 0xa3, 0x49, 0xf4, 0x2a, 0x04, 0x00, 0x00,
}
